### ISSUE TITLE
Wasserzeichen 

### ISSUE THREAD

**Issue by dleisegang** [blaetter/pepgen#1]
Das Wasserzeichen (bzw. der Platzhalter) ist auf der Seite mit dem Titelbild verschwunden.

![bildschirmfoto 2017-09-14 um 15 28 47](https://user-images.githubusercontent.com/2465369/30432386-c4a164f6-9961-11e7-9b19-a60d3214f1ed.png)

Auch im Impressum ist es nicht mehr da.

![bildschirmfoto 2017-09-14 um 15 28 53](https://user-images.githubusercontent.com/2465369/30432417-ecdb72fe-9961-11e7-8916-857f8342ee17.png)

**Comment by ambo** [comment]
This issue was moved to ambo/www.blaetter.de#41
