### ISSUE TITLE
Einschub

### ISSUE THREAD

**Issue by dleisegang** [blaetter/pepgen#2]
Können wir diese Zeile ohne Einschub machen? Vermutlich zu kompliziert, oder?

Wie sieht es mit einer Leerzeile davor aus?

Wäre es möglich, diese Zeile vor die erste Fußnote zu stellen? (Kenne die Antwort.) ;)

![bildschirmfoto 2017-09-14 um 15 27 58](https://user-images.githubusercontent.com/2465369/30432466-13c7676a-9962-11e7-8114-9a258958429b.png)

**Comment by dleisegang** [comment]
Hier genauso:

![bildschirmfoto 2017-09-14 um 15 26 08](https://user-images.githubusercontent.com/2465369/30432779-eb00c7d0-9962-11e7-95b0-5a79d8a37332.png)

**Comment by ambo** [comment]
This issue was moved to ambo/www.blaetter.de#42
