### ISSUE TITLE
Auflösung Titelbild

### ISSUE THREAD

**Issue by dleisegang** [blaetter/pepgen#3]
Wir sollten ein Bild mit besserer Auflösung hinterlegen, mind. 1024x700px

![bildschirmfoto 2017-09-14 um 15 27 02](https://user-images.githubusercontent.com/2465369/30432555-4e4f137e-9962-11e7-8201-abc260e1d7f1.png)

**Comment by ambo** [comment]
Der Mechanismus nimmt das Bild aus der Online-Ausgabe. Könnt ihr dort eine höher aufgelöste Variante einstellen?

**Comment by ambo** [comment]
This issue was moved to ambo/www.blaetter.de#43
