### ISSUE TITLE
Übersetzung

### ISSUE THREAD

**Issue by dleisegang** [blaetter/pepgen#4]
Können wir das übersetzen? – Cover Page, Table of Content...

![bildschirmfoto 2017-09-14 um 15 26 53](https://user-images.githubusercontent.com/2465369/30432584-653155fc-9962-11e7-8c3f-b52506a68a19.png)

**Comment by ambo** [comment]
Auf jeden Fall.

**Comment by ambo** [comment]
This issue was moved to ambo/www.blaetter.de#44
