### ISSUE TITLE
Abstände Titel

### ISSUE THREAD

**Issue by dleisegang** [blaetter/pepgen#5]
Der Abstand zwischen Rubrik und Titel ist ok.
Es sollte nur kein so großer Abstand zwischen Titel, Untertitel und AutorIn sein.

![bildschirmfoto 2017-09-14 um 15 26 36](https://user-images.githubusercontent.com/2465369/30432658-9d14f870-9962-11e7-9ac0-ba829d1212c5.png)

![bildschirmfoto 2017-09-14 um 15 25 37](https://user-images.githubusercontent.com/2465369/30432675-a81fc60a-9962-11e7-9b3b-b6f11b9e9a2e.png)

**Comment by ambo** [comment]
This issue was moved to ambo/www.blaetter.de#45
