### ISSUE TITLE
Format Untertitel

### ISSUE THREAD

**Issue by dleisegang** [blaetter/pepgen#6]
Der Untertitel sollte die Schriftart des Obertitels (non-serif) haben, nur nicht fett (wie "von")

![bildschirmfoto 2017-09-14 um 15 25 37](https://user-images.githubusercontent.com/2465369/30432729-ca3b899a-9962-11e7-8ee7-d7e2a1ee2e99.png)

**Comment by ambo** [comment]
This issue was moved to ambo/www.blaetter.de#46
