### ISSUE TITLE
Initial

### ISSUE THREAD

**Issue by dleisegang** [blaetter/pepgen#7]
In Adobe Digital Editions und mit dem EPUBReader-Addon für Firefox wird das Initial nicht angezeigt. Mit iBook schon...

![bildschirmfoto 2017-09-14 um 15 42 13](https://user-images.githubusercontent.com/2465369/30433129-eea1913e-9963-11e7-9d26-c5b6f87b32cb.png)

Dort, wo das Initial nicht angezeigt wird, erscheint ein Leerzeichen:

![bildschirmfoto 2017-09-14 um 15 50 22](https://user-images.githubusercontent.com/2465369/30433371-984c622c-9964-11e7-9dbc-6a1acfccd162.png)

**Comment by ambo** [comment]
This issue was moved to ambo/www.blaetter.de#47
